/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoRouteImport } from './routes/$produto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as ProdutoIndexRouteImport } from './routes/$produto.index'
import { Route as ProdutoEmpresaRouteImport } from './routes/$produto.$empresa'
import { Route as ProdutoEmpresaIndexRouteImport } from './routes/$produto.$empresa.index'
import { Route as ProdutoEmpresaAuthRouteImport } from './routes/$produto.$empresa.auth'
import { Route as ProdutoEmpresaConfiguracaoRouteImport } from './routes/$produto.$empresa.configuracao'
import { Route as ProdutoEmpresaContratosRouteImport } from './routes/$produto.$empresa.contratos'
import { Route as ProdutoEmpresaContratosIdRouteImport } from './routes/$produto.$empresa.contratos.$id'
import { Route as ProdutoEmpresaSolicitacoesIdRouteImport } from './routes/$produto.$empresa.solicitacoes.$id'
import { Route as ProdutoEmpresaNegociacaoIdRouteImport } from './routes/$produto.$empresa.negociacao.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/$produto',
  path: '/$produto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIndexRoute = ProdutoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutoRoute,
} as any)
const ProdutoEmpresaRoute = ProdutoEmpresaRouteImport.update({
  id: '/$empresa',
  path: '/$empresa',
  getParentRoute: () => ProdutoRoute,
} as any)
const ProdutoEmpresaIndexRoute = ProdutoEmpresaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutoEmpresaRoute,
} as any)
const ProdutoEmpresaAuthRoute = ProdutoEmpresaAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => ProdutoEmpresaRoute,
} as any)
const ProdutoEmpresaConfiguracaoRoute =
  ProdutoEmpresaConfiguracaoRouteImport.update({
    id: '/configuracao',
    path: '/configuracao',
    getParentRoute: () => ProdutoEmpresaRoute,
  } as any)
const ProdutoEmpresaContratosRoute = ProdutoEmpresaContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => ProdutoEmpresaRoute,
} as any)
const ProdutoEmpresaContratosIdRoute =
  ProdutoEmpresaContratosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProdutoEmpresaContratosRoute,
  } as any)
const ProdutoEmpresaSolicitacoesIdRoute =
  ProdutoEmpresaSolicitacoesIdRouteImport.update({
    id: '/solicitacoes/$id',
    path: '/solicitacoes/$id',
    getParentRoute: () => ProdutoEmpresaRoute,
  } as any)
const ProdutoEmpresaNegociacaoIdRoute =
  ProdutoEmpresaNegociacaoIdRouteImport.update({
    id: '/negociacao/$id',
    path: '/negociacao/$id',
    getParentRoute: () => ProdutoEmpresaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$produto': typeof ProdutoRouteWithChildren
  '/auth': typeof AuthRoute
  '/superadmin': typeof SuperadminRoute
  '/$produto/$empresa': typeof ProdutoEmpresaRouteWithChildren
  '/$produto/': typeof ProdutoIndexRoute
  '/$produto/$empresa/auth': typeof ProdutoEmpresaAuthRoute
  '/$produto/$empresa/configuracao': typeof ProdutoEmpresaConfiguracaoRoute
  '/$produto/$empresa/contratos': typeof ProdutoEmpresaContratosRouteWithChildren
  '/$produto/$empresa/': typeof ProdutoEmpresaIndexRoute
  '/$produto/$empresa/contratos/$id': typeof ProdutoEmpresaContratosIdRoute
  '/$produto/$empresa/solicitacoes/$id': typeof ProdutoEmpresaSolicitacoesIdRoute
  '/$produto/$empresa/negociacao/$id': typeof ProdutoEmpresaNegociacaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/superadmin': typeof SuperadminRoute
  '/$produto': typeof ProdutoIndexRoute
  '/$produto/$empresa/auth': typeof ProdutoEmpresaAuthRoute
  '/$produto/$empresa/configuracao': typeof ProdutoEmpresaConfiguracaoRoute
  '/$produto/$empresa/contratos': typeof ProdutoEmpresaContratosRouteWithChildren
  '/$produto/$empresa': typeof ProdutoEmpresaIndexRoute
  '/$produto/$empresa/contratos/$id': typeof ProdutoEmpresaContratosIdRoute
  '/$produto/$empresa/solicitacoes/$id': typeof ProdutoEmpresaSolicitacoesIdRoute
  '/$produto/$empresa/negociacao/$id': typeof ProdutoEmpresaNegociacaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$produto': typeof ProdutoRouteWithChildren
  '/auth': typeof AuthRoute
  '/superadmin': typeof SuperadminRoute
  '/$produto/$empresa': typeof ProdutoEmpresaRouteWithChildren
  '/$produto/': typeof ProdutoIndexRoute
  '/$produto/$empresa/auth': typeof ProdutoEmpresaAuthRoute
  '/$produto/$empresa/configuracao': typeof ProdutoEmpresaConfiguracaoRoute
  '/$produto/$empresa/contratos': typeof ProdutoEmpresaContratosRouteWithChildren
  '/$produto/$empresa/': typeof ProdutoEmpresaIndexRoute
  '/$produto/$empresa/contratos/$id': typeof ProdutoEmpresaContratosIdRoute
  '/$produto/$empresa/solicitacoes/$id': typeof ProdutoEmpresaSolicitacoesIdRoute
  '/$produto/$empresa/negociacao/$id': typeof ProdutoEmpresaNegociacaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$produto'
    | '/auth'
    | '/superadmin'
    | '/$produto/$empresa'
    | '/$produto/'
    | '/$produto/$empresa/auth'
    | '/$produto/$empresa/configuracao'
    | '/$produto/$empresa/contratos'
    | '/$produto/$empresa/'
    | '/$produto/$empresa/contratos/$id'
    | '/$produto/$empresa/solicitacoes/$id'
    | '/$produto/$empresa/negociacao/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/superadmin'
    | '/$produto'
    | '/$produto/$empresa/auth'
    | '/$produto/$empresa/configuracao'
    | '/$produto/$empresa/contratos'
    | '/$produto/$empresa'
    | '/$produto/$empresa/contratos/$id'
    | '/$produto/$empresa/solicitacoes/$id'
    | '/$produto/$empresa/negociacao/$id'
  id:
    | '__root__'
    | '/'
    | '/$produto'
    | '/auth'
    | '/superadmin'
    | '/$produto/$empresa'
    | '/$produto/'
    | '/$produto/$empresa/auth'
    | '/$produto/$empresa/configuracao'
    | '/$produto/$empresa/contratos'
    | '/$produto/$empresa/'
    | '/$produto/$empresa/contratos/$id'
    | '/$produto/$empresa/solicitacoes/$id'
    | '/$produto/$empresa/negociacao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProdutoRoute: typeof ProdutoRouteWithChildren
  AuthRoute: typeof AuthRoute
  SuperadminRoute: typeof SuperadminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$produto': {
      id: '/$produto'
      path: '/$produto'
      fullPath: '/$produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$produto/': {
      id: '/$produto/'
      path: '/'
      fullPath: '/$produto/'
      preLoaderRoute: typeof ProdutoIndexRouteImport
      parentRoute: typeof ProdutoRoute
    }
    '/$produto/$empresa': {
      id: '/$produto/$empresa'
      path: '/$empresa'
      fullPath: '/$produto/$empresa'
      preLoaderRoute: typeof ProdutoEmpresaRouteImport
      parentRoute: typeof ProdutoRoute
    }
    '/$produto/$empresa/': {
      id: '/$produto/$empresa/'
      path: '/'
      fullPath: '/$produto/$empresa/'
      preLoaderRoute: typeof ProdutoEmpresaIndexRouteImport
      parentRoute: typeof ProdutoEmpresaRoute
    }
    '/$produto/$empresa/auth': {
      id: '/$produto/$empresa/auth'
      path: '/auth'
      fullPath: '/$produto/$empresa/auth'
      preLoaderRoute: typeof ProdutoEmpresaAuthRouteImport
      parentRoute: typeof ProdutoEmpresaRoute
    }
    '/$produto/$empresa/configuracao': {
      id: '/$produto/$empresa/configuracao'
      path: '/configuracao'
      fullPath: '/$produto/$empresa/configuracao'
      preLoaderRoute: typeof ProdutoEmpresaConfiguracaoRouteImport
      parentRoute: typeof ProdutoEmpresaRoute
    }
    '/$produto/$empresa/contratos': {
      id: '/$produto/$empresa/contratos'
      path: '/contratos'
      fullPath: '/$produto/$empresa/contratos'
      preLoaderRoute: typeof ProdutoEmpresaContratosRouteImport
      parentRoute: typeof ProdutoEmpresaRoute
    }
    '/$produto/$empresa/contratos/$id': {
      id: '/$produto/$empresa/contratos/$id'
      path: '/$id'
      fullPath: '/$produto/$empresa/contratos/$id'
      preLoaderRoute: typeof ProdutoEmpresaContratosIdRouteImport
      parentRoute: typeof ProdutoEmpresaContratosRoute
    }
    '/$produto/$empresa/solicitacoes/$id': {
      id: '/$produto/$empresa/solicitacoes/$id'
      path: '/solicitacoes/$id'
      fullPath: '/$produto/$empresa/solicitacoes/$id'
      preLoaderRoute: typeof ProdutoEmpresaSolicitacoesIdRouteImport
      parentRoute: typeof ProdutoEmpresaRoute
    }
    '/$produto/$empresa/negociacao/$id': {
      id: '/$produto/$empresa/negociacao/$id'
      path: '/negociacao/$id'
      fullPath: '/$produto/$empresa/negociacao/$id'
      preLoaderRoute: typeof ProdutoEmpresaNegociacaoIdRouteImport
      parentRoute: typeof ProdutoEmpresaRoute
    }
  }
}

interface ProdutoEmpresaContratosRouteChildren {
  ProdutoEmpresaContratosIdRoute: typeof ProdutoEmpresaContratosIdRoute
}

const ProdutoEmpresaContratosRouteChildren: ProdutoEmpresaContratosRouteChildren =
  {
    ProdutoEmpresaContratosIdRoute: ProdutoEmpresaContratosIdRoute,
  }

const ProdutoEmpresaContratosRouteWithChildren =
  ProdutoEmpresaContratosRoute._addFileChildren(
    ProdutoEmpresaContratosRouteChildren,
  )

interface ProdutoEmpresaRouteChildren {
  ProdutoEmpresaAuthRoute: typeof ProdutoEmpresaAuthRoute
  ProdutoEmpresaConfiguracaoRoute: typeof ProdutoEmpresaConfiguracaoRoute
  ProdutoEmpresaContratosRoute: typeof ProdutoEmpresaContratosRouteWithChildren
  ProdutoEmpresaIndexRoute: typeof ProdutoEmpresaIndexRoute
  ProdutoEmpresaSolicitacoesIdRoute: typeof ProdutoEmpresaSolicitacoesIdRoute
  ProdutoEmpresaNegociacaoIdRoute: typeof ProdutoEmpresaNegociacaoIdRoute
}

const ProdutoEmpresaRouteChildren: ProdutoEmpresaRouteChildren = {
  ProdutoEmpresaAuthRoute: ProdutoEmpresaAuthRoute,
  ProdutoEmpresaConfiguracaoRoute: ProdutoEmpresaConfiguracaoRoute,
  ProdutoEmpresaContratosRoute: ProdutoEmpresaContratosRouteWithChildren,
  ProdutoEmpresaIndexRoute: ProdutoEmpresaIndexRoute,
  ProdutoEmpresaSolicitacoesIdRoute: ProdutoEmpresaSolicitacoesIdRoute,
  ProdutoEmpresaNegociacaoIdRoute: ProdutoEmpresaNegociacaoIdRoute,
}

const ProdutoEmpresaRouteWithChildren = ProdutoEmpresaRoute._addFileChildren(
  ProdutoEmpresaRouteChildren,
)

interface ProdutoRouteChildren {
  ProdutoEmpresaRoute: typeof ProdutoEmpresaRouteWithChildren
  ProdutoIndexRoute: typeof ProdutoIndexRoute
}

const ProdutoRouteChildren: ProdutoRouteChildren = {
  ProdutoEmpresaRoute: ProdutoEmpresaRouteWithChildren,
  ProdutoIndexRoute: ProdutoIndexRoute,
}

const ProdutoRouteWithChildren =
  ProdutoRoute._addFileChildren(ProdutoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProdutoRoute: ProdutoRouteWithChildren,
  AuthRoute: AuthRoute,
  SuperadminRoute: SuperadminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
